### PR TITLE
legend text

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
image
on mobile

image
on desktop

(note I am working on the z-index stuff elsewhere)

**Comment by amrhoades** [comment]
@jread-usgs can you change the text color to a dark-ish grey for 0-0.1?

**Comment by amrhoades** [comment]
Also wondering if it should be:

Hourly rainfall amount (inches)

And instead of >0.8, it is 0.8+

**Comment by amrhoades** [comment]
Remove italics for hourly rainfall amount and make it the same text size as 'hurricane irma' and 'usgs stream gages'

**Pull request merged**
